name: publish
on:
  release:
    types: [published]
    branches:
      - master # Default release branch
jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Create package(s)
        run: dotnet pack --configuration Release --no-build

      - name: Publish packages
        run: dotnet nuget push **/*.nupkg -k ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
